export const tagOptions = [
  "culinary",
  "staffing",
  "timing",
  "setup",
  "client complaint",
  "client praise",
  "equipment",
  "communication",
  "follow-up needed",
];

export const eventTypes = [
  "Wedding",
  "Corporate",
  "Fundraiser",
  "Gala",
  "Private Dinner",
  "Conference",
  "Other",
];

export const seedReviews = [
  {
    id: "rev-1001",
    clientName: "Harbor Point Leadership Dinner",
    clientContact: "Jordan Lee",
    eventDate: "2026-06-06",
    venue: "Live Oak Ballroom",
    eventType: "Corporate",
    managerName: "Michael Frazier",
    staffInvolved: ["A. Lewis", "J. Carter", "M. Benton"],
    overallRating: 4,
    summary:
      "Smooth executive dinner with strong room flow and attentive table service. The client praised pacing and room reset speed.",
    culinaryNotes:
      "Entrees landed hot and consistent. Two guests requested alternate sauces and culinary handled both quickly.",
    consumption: {
      coke: 12,
      dietCoke: 8,
      sprite: 6,
      sparklingWater: 18,
      stillWater: 36,
      trailMix: 0,
      chips: 0,
      oranges: 8,
      bananas: 6,
      apples: 10,
      pears: 4,
    },
    operationalNotes:
      "Initial AV check ran behind because the podium mic was not labeled. Banquet captain adjusted the timeline without client impact.",
    clientFeedback:
      "Client asked for the same core team on the next quarterly dinner.",
    wins: "Staff kept water service tight and handled late seating changes calmly.",
    issues: "Need a clearer pre-event AV ownership check.",
    tags: ["client praise", "communication", "equipment"],
    followUpStatus: "Draft",
    followUpOwner: "",
    followUpDueDate: "",
    followUpNotes: "",
    attachments: [
      {
        id: "att-1001",
        name: "signed-bEO.pdf",
        type: "application/pdf",
        size: 348210,
        uploadedAt: "2026-06-07T13:20:00.000Z",
      },
    ],
    createdAt: "2026-06-07T13:10:00.000Z",
    updatedAt: "2026-06-07T14:05:00.000Z",
  },
  {
    id: "rev-1002",
    clientName: "Carter-Wells Wedding",
    clientContact: "Avery Wells",
    eventDate: "2026-06-08",
    venue: "Garden Pavilion",
    eventType: "Wedding",
    managerName: "Michael Frazier",
    staffInvolved: ["R. Mason", "T. Evans", "K. Hill", "S. Patel"],
    overallRating: 3,
    summary:
      "Guest experience recovered well after a delayed vendor arrival. Couple was happy by end of night, but the timeline needs review.",
    culinaryNotes:
      "Late-night sliders were popular. Vegetarian count was short by three plates and culinary produced replacements within eight minutes.",
    consumption: {
      coke: 24,
      dietCoke: 10,
      sprite: 14,
      sparklingWater: 30,
      stillWater: 64,
      trailMix: 12,
      chips: 18,
      oranges: 10,
      bananas: 12,
      apples: 16,
      pears: 8,
    },
    operationalNotes:
      "Photo booth vendor arrived during salad course and crossed through the main service lane.",
    clientFeedback:
      "Planner appreciated the recovery but asked for a post-event note on vendor arrival controls.",
    wins: "Captain communicated clearly with planner and DJ during timeline compression.",
    issues: "Vendor access and vegetarian count confirmation need follow-up.",
    tags: ["culinary", "timing", "follow-up needed", "communication"],
    followUpStatus: "Needs follow-up",
    followUpOwner: "",
    followUpDueDate: "",
    followUpNotes: "Send the planner a concise recovery note covering vendor arrival controls and vegetarian count confirmation.",
    attachments: [
      {
        id: "att-1002",
        name: "room-reset-photo.jpg",
        type: "image/jpeg",
        size: 802455,
        uploadedAt: "2026-06-09T01:42:00.000Z",
      },
    ],
    createdAt: "2026-06-09T01:30:00.000Z",
    updatedAt: "2026-06-09T02:15:00.000Z",
  },
  {
    id: "rev-1003",
    clientName: "Lowcountry Arts Fundraiser",
    clientContact: "Morgan Pierce",
    eventDate: "2026-06-02",
    venue: "River Hall",
    eventType: "Fundraiser",
    managerName: "Dana Rivers",
    staffInvolved: ["M. Benton", "L. Moore"],
    overallRating: 4,
    summary:
      "Review pending final client call. Early notes indicate strong cocktail hour execution and minor setup confusion.",
    culinaryNotes:
      "Passed apps were well received. Need to confirm whether the client wants the oyster station repeated next year.",
    consumption: {
      coke: 18,
      dietCoke: 12,
      sprite: 9,
      sparklingWater: 22,
      stillWater: 48,
      trailMix: 8,
      chips: 14,
      oranges: 12,
      bananas: 9,
      apples: 12,
      pears: 6,
    },
    operationalNotes:
      "Silent auction table numbers changed after floor plan printout.",
    clientFeedback: "Awaiting final call.",
    wins: "Bar line stayed short through peak arrival.",
    issues: "Floor plan update process should be tightened.",
    tags: ["setup", "staffing"],
    followUpStatus: "Draft",
    followUpOwner: "",
    followUpDueDate: "",
    followUpNotes: "",
    attachments: [],
    createdAt: "2026-06-03T15:00:00.000Z",
    updatedAt: "2026-06-03T15:00:00.000Z",
  },
];
